import 'dart:io';
import 'package:camera/camera.dart';
import 'dart:async';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:onnxruntime/onnxruntime.dart';

import 'liveness_types.dart';
import 'liveness_screen.dart';
import 'face_match_screen.dart';
import 'face_match_engine.dart';
import 'anti_spoof_engine.dart';
import 'liveness_guard.dart';

export 'liveness_guard.dart'
    show
        LicenseException,
        LicenseExpiredException,
        LicensePackageMismatchException,
        LicenseTamperedException,
        LicenseFormatException;

/// Main entry point for the Liveness Flutter SDK on Mobile.
///
/// **IMPORTANT — call [initialize] before any other method.**
class FlutterFaceNova {
  static final FaceMatchEngine _faceMatchEngine = FaceMatchEngine();
  static final AntiSpoofEngine _antiSpoofEngine = AntiSpoofEngine();

  /// Initializes the SDK with your offline license key.
  ///
  /// [licenseKey] — the token generated by the `generate_license_key.py` script.
  ///
  /// The package name is verified automatically by native C++ against the OS —
  /// no need to pass it from Dart.
  ///
  /// Throws a [LicenseException] subclass if the key is invalid, expired,
  /// or for the wrong package. All other SDK methods silently return null
  /// until this call succeeds.
  ///
  /// Example:
  /// ```dart
  /// await FlutterFaceNova.initialize(licenseKey: 'ABC123==');
  /// ```
  static Future<void> initialize({
    required String licenseKey,
  }) async {
    await LivenessGuard.verifyLicense(licenseKey);
    // Pre-load all models immediately after license verification so the first
    // liveness/face-compare call is instant instead of waiting 15-20 seconds.
    OrtEnv.instance.init();
    await Future.wait([
      _antiSpoofEngine.load(),
      _faceMatchEngine.load(),
    ]);
  }

  /// Whether the SDK has been successfully initialized with a valid license.
  static bool get isInitialized => LivenessGuard.isVerified;

  /// Starts the liveness detection UI.
  ///
  /// Returns [LivenessResult] or null if not initialized / permission denied.
  ///
  /// [livenessThreshold] — front camera strictness, 0.0–1.0.
  ///   Defaults: iOS 0.60, Android 0.30.
  /// [backCameraThreshold] — back camera strictness, 0.0–1.0.
  ///   Defaults: iOS 0.90, Android 0.80.
  static Future<LivenessResult?> startLiveness(
    BuildContext context, {
    double? livenessThreshold,
    double? backCameraThreshold,
  }) async {
    if (!LivenessGuard.isVerified) {
      debugPrint('[FlutterFaceNova] SDK not initialized. Call initialize() first.');
      return null;
    }

    final frontThreshold = livenessThreshold   ?? (Platform.isIOS ? 0.60 : 0.30);
    final backThreshold  = backCameraThreshold ?? (Platform.isIOS ? 0.90 : 0.80);

    final cameras = await availableCameras();
    if (!context.mounted) return null;

    return await Navigator.push<LivenessResult>(
      context,
      MaterialPageRoute(
        builder: (_) => LivenessScreen(
          cameras: cameras,
          livenessThreshold: frontThreshold,
          backCameraThreshold: backThreshold,
          preloadedEngine: _antiSpoofEngine,
        ),
      ),
    );
  }

  /// Generates a 128D face embedding from [imageBytes].
  ///
  /// Returns [FaceMetadataResult] or null if not initialized.
  static Future<FaceMetadataResult?> generateFaceMetadata(
    Uint8List imageBytes,
  ) async {
    if (!LivenessGuard.isVerified) {
      debugPrint('[FlutterFaceNova] SDK not initialized. Call initialize() first.');
      return null;
    }

    try {
      await _faceMatchEngine.load();
      final mapResult = await _faceMatchEngine.generateMetadata(imageBytes);
      final floatList = mapResult['metadata'] as List<double>;
      final croppedImage = mapResult['croppedImage'] as Uint8List;

      final float32List = Float32List.fromList(floatList);
      return FaceMetadataResult(
        metadata: float32List.buffer.asUint8List(),
        croppedImage: croppedImage,
      );
    } catch (e) {
      debugPrint('[FlutterFaceNova] Error generating face metadata: $e');
      return null;
    }
  }

  /// Runs liveness detection and face matching in a single camera session.
  ///
  /// Opens the camera once. When liveness passes the captured frame is used
  /// directly for face matching — no second camera open needed.
  ///
  /// Returns [FaceMatchResult] or null if liveness failed / cancelled.
  static Future<FaceMatchResult?> startLivenessAndMatch(
    BuildContext context, {
    required List<FaceEntry> enrolledFaces,
    double? livenessThreshold,
    double? backCameraThreshold,
    double matchThreshold = 75.0,
  }) async {
    if (!LivenessGuard.isVerified) {
      debugPrint('[FlutterFaceNova] SDK not initialized. Call initialize() first.');
      return null;
    }
    if (enrolledFaces.isEmpty) {
      debugPrint('[FlutterFaceNova] No enrolled faces provided.');
      return null;
    }

    final frontThreshold = livenessThreshold   ?? (Platform.isIOS ? 0.60 : 0.30);
    final backThreshold  = backCameraThreshold ?? (Platform.isIOS ? 0.90 : 0.80);

    final cameras = await availableCameras();
    if (!context.mounted) return null;

    final liveness = await Navigator.push<LivenessResult>(
      context,
      MaterialPageRoute(
        builder: (_) => LivenessScreen(
          cameras: cameras,
          livenessThreshold: frontThreshold,
          backCameraThreshold: backThreshold,
          preloadedEngine: _antiSpoofEngine,
        ),
      ),
    );

    if (liveness == null || !liveness.isReal || liveness.imageBytes == null) return null;

    try {
      await _faceMatchEngine.load();
      final matchData    = await _faceMatchEngine.generateMetadata(liveness.imageBytes!);
      final capturedMeta = matchData['metadata'] as List<double>;
      final capturedImg  = matchData['croppedImage'] as Uint8List;

      double bestScore = 0;
      FaceEntry? bestMatch;
      for (final face in enrolledFaces) {
        final enrolled = Float32List.view(face.metadata.buffer).toList();
        final score    = _faceMatchEngine.compare(capturedMeta, enrolled);
        if (score > bestScore) { bestScore = score; bestMatch = face; }
      }

      return FaceMatchResult(
        matchedFace: bestMatch,
        score: bestScore,
        isMatch: bestScore >= matchThreshold,
        capturedImage: capturedImg,
      );
    } catch (e) {
      debugPrint('[FlutterFaceNova] Face match error after liveness: $e');
      return null;
    }
  }

  /// Matches [imageBytes] against [enrolledFaces] without opening the camera.
  ///
  /// Use this after [startLiveness] passes to do face matching on the liveness
  /// frame — giving you full control over progress UI between the two steps.
  ///
  /// Returns [FaceMatchResult] or null if no face detected / not initialized.
  static Future<FaceMatchResult?> matchFaceFromImage(
    Uint8List imageBytes, {
    required List<FaceEntry> enrolledFaces,
    double matchThreshold = 75.0,
  }) async {
    if (!LivenessGuard.isVerified) {
      debugPrint('[FlutterFaceNova] SDK not initialized. Call initialize() first.');
      return null;
    }
    if (enrolledFaces.isEmpty) return null;

    try {
      await _faceMatchEngine.load();
      final matchData    = await _faceMatchEngine.generateMetadata(imageBytes);
      final capturedMeta = matchData['metadata'] as List<double>;
      final capturedImg  = matchData['croppedImage'] as Uint8List;

      double bestScore = 0;
      FaceEntry? bestMatch;
      for (final face in enrolledFaces) {
        final enrolled = Float32List.view(face.metadata.buffer).toList();
        final score    = _faceMatchEngine.compare(capturedMeta, enrolled);
        if (score > bestScore) { bestScore = score; bestMatch = face; }
      }

      return FaceMatchResult(
        matchedFace: bestMatch,
        score: bestScore,
        isMatch: bestScore >= matchThreshold,
        capturedImage: capturedImg,
      );
    } catch (e) {
      debugPrint('[FlutterFaceNova] matchFaceFromImage error: $e');
      return null;
    }
  }

  /// Opens a camera screen that scans a face and compares it against [enrolledFaces].
  ///
  /// Returns [FaceMatchResult] with the best match and score, or null if cancelled.
  /// [matchThreshold] — score (0–100) above which a face is considered matched (default 75).
  static Future<FaceMatchResult?> startFaceMatch(
    BuildContext context, {
    required List<FaceEntry> enrolledFaces,
    double matchThreshold = 75.0,
  }) async {
    if (!LivenessGuard.isVerified) {
      debugPrint('[FlutterFaceNova] SDK not initialized. Call initialize() first.');
      return null;
    }
    if (enrolledFaces.isEmpty) {
      debugPrint('[FlutterFaceNova] No enrolled faces provided.');
      return null;
    }

    await _faceMatchEngine.load();
    final cameras = await availableCameras();
    if (!context.mounted) return null;

    return await Navigator.push<FaceMatchResult>(
      context,
      MaterialPageRoute(
        builder: (_) => FaceMatchScreen(
          cameras: cameras,
          enrolledFaces: enrolledFaces,
          preloadedEngine: _faceMatchEngine,
          matchThreshold: matchThreshold,
        ),
      ),
    );
  }

  /// Compares two metadata arrays and returns a match percentage (0 to 100).
  ///
  /// A score ≥ 80 indicates a strong match.
  /// [matchThreshold] — cosine similarity threshold (default 0.363, SFace standard).
  static double compareFaceMetadata(
    Uint8List metadata1,
    Uint8List metadata2, {
    double matchThreshold = 0.363,
  }) {
    final floatList1 = Float32List.view(metadata1.buffer);
    final floatList2 = Float32List.view(metadata2.buffer);

    if (floatList1.length != floatList2.length) return 0.0;
    int len = floatList1.length;

    double dotProduct = 0.0;
    for (int i = 0; i < len; i++) {
      dotProduct += floatList1[i] * floatList2[i];
    }

    double similarity = dotProduct;
    double percentage;
    if (similarity >= matchThreshold) {
      percentage =
          80.0 + ((similarity - matchThreshold) / (1.0 - matchThreshold)) * 20.0;
    } else {
      percentage = ((similarity + 1.0) / (matchThreshold + 1.0)) * 79.0;
      if (percentage < 0) percentage = 0;
    }

    return percentage.clamp(0.0, 100.0);
  }
}
