import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:flutter_face_nova/flutter_face_nova.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:uuid/uuid.dart';

import 'enrolled_face.dart';
import 'settings_screen.dart';
import 'settings_store.dart';
import 'store_preview_screen.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Replace with your own key generated by generate_license_key.py
// ─────────────────────────────────────────────────────────────────────────────
// Android: com.liveness.liveness_app  — key below (expires 2126-06-30)
// iOS:     com.liveness.livenessApp   — key below (expires 2027-12-31)
const _kLicenseKeyAndroid =
    'LxkrQhkdAlYcLkAKcV5fVykYIx8GKxVDAjcBSG0EGxF6W3VcCT4zfVkpYEEydGVq'
    'ODMzQzQSIUcxOmNLM39wcXgzCjg7B0MLNw4CEDFadGRx';

const _kLicenseKeyIOS =
    'LxkrQhkdAlYcLkAKcV5fVykYIx8GNQRDDnkDS2gfBxNhRXcQR0YiYQomRE0aRkcX'
    'GzUMXk0OJnldfgA4O1pSaSQbBCY+RAFDGwV2G2d1Dhw=';

// Brand colours
const _kBlue       = Color(0xFF1565C0);
const _kBlueMid    = Color(0xFF1976D2);
const _kGreen      = Color(0xFF00897B);
const _kTextPri    = Color(0xFF0D1B2A);
const _kTextSec    = Color(0xFF546E7A);
const _kTextHint   = Color(0xFF90A4AE);
const _kSurface    = Color(0xFFF5F7FA);
const _kBorder     = Color(0xFFE3E8EF);
const _kRed        = Color(0xFFE53935);

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await FaceStore.init();
  await SettingsStore.init();
  await Permission.camera.request();
  runApp(const ExampleApp());
}

// ─────────────────────────────────────────────────────────────────────────────

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FaceNova',
      theme: ThemeData(
        brightness: Brightness.light,
        scaffoldBackgroundColor: Colors.white,
        colorScheme: ColorScheme.fromSeed(
          seedColor: _kBlue,
          brightness: Brightness.light,
        ),
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Home Screen
// ─────────────────────────────────────────────────────────────────────────────

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

enum _MatchStep { idle, liveness, matching }

class _HomeScreenState extends State<HomeScreen> {
  List<EnrolledFace> _enrolled       = [];
  FaceMatchResult?   _matchResult;
  LivenessResult?    _livenessFailResult;
  _MatchStep         _step = _MatchStep.idle;
  bool               _enrolling = false;

  @override
  void initState() {
    super.initState();
    _reload();
    WidgetsBinding.instance.addPostFrameCallback((_) => _initSdk());
  }

  Future<void> _initSdk() async {
    try {
      final key = Platform.isIOS ? _kLicenseKeyIOS : _kLicenseKeyAndroid;
      await LivenessFlutter.initialize(licenseKey: key);
    } catch (e) {
      debugPrint('[Example] SDK init failed: $e');
    }
    if (mounted) setState(() {});
  }

  void _reload() => setState(() => _enrolled = FaceStore.getAll());

  // ── Enroll from gallery ────────────────────────────────────────────────────
  Future<void> _enrollFromGallery() async {
    if (_step != _MatchStep.idle) return;
    final picker = ImagePicker();
    final xfile  = await picker.pickImage(source: ImageSource.gallery, imageQuality: 80);
    if (xfile == null || !mounted) return;

    final bytes = await xfile.readAsBytes();
    if (!mounted) return;

    setState(() { _step = _MatchStep.liveness; _enrolling = true; });
    try {
      final meta = await LivenessFlutter.generateFaceMetadata(bytes);
      if (meta == null) {
        _showSnack('Could not detect a face in that image.');
        return;
      }

      final name = await _askName();
      if (name == null || name.trim().isEmpty) return;

      final face = EnrolledFace(
        id:       const Uuid().v4(),
        name:     name.trim(),
        metadata: meta.metadata,
        photo:    meta.croppedImage,
      );
      await FaceStore.add(face);
      _reload();
      _showSnack('${face.name} enrolled.');
    } finally {
      if (mounted) setState(() { _step = _MatchStep.idle; _enrolling = false; });
    }
  }

  Future<String?> _askName() => showDialog<String>(
        context: context,
        builder: (ctx) {
          final ctrl = TextEditingController();
          return AlertDialog(
            title: const Text('Enter name', style: TextStyle(color: _kTextPri)),
            content: TextField(
              controller: ctrl,
              autofocus: true,
              style: const TextStyle(color: _kTextPri),
              decoration: const InputDecoration(hintText: 'Full name'),
            ),
            actions: [
              TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel')),
              TextButton(
                onPressed: () => Navigator.pop(ctx, ctrl.text),
                child: const Text('Save', style: TextStyle(color: _kBlue)),
              ),
            ],
          );
        },
      );

  // ── Liveness → face match ─────────────────────────────────────────────────
  Future<void> _startFaceMatch() async {
    if (_step != _MatchStep.idle) return;
    if (_enrolled.isEmpty) { _showSnack('Enroll at least one face first.'); return; }

    setState(() {
      _step               = _MatchStep.liveness;
      _matchResult        = null;
      _livenessFailResult = null;
    });

    final liveness = await LivenessFlutter.startLiveness(
      context,
      livenessThreshold: SettingsStore.livenessThreshold,
      backCameraThreshold: SettingsStore.backCameraThreshold,
    );
    if (!mounted) return;

    if (liveness == null || !liveness.isReal) {
      setState(() { _step = _MatchStep.idle; _livenessFailResult = liveness; });
      return;
    }

    setState(() => _step = _MatchStep.matching);

    bool dialogOpen = true;
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => const _VerifyingDialog(),
    ).then((_) => dialogOpen = false);

    final entries = _enrolled.map((e) => FaceEntry(
      id: e.id, name: e.name, metadata: e.metadata, photo: e.photo,
    )).toList();

    final result = await LivenessFlutter.matchFaceFromImage(
      liveness.imageBytes!,
      enrolledFaces: entries,
      matchThreshold: SettingsStore.matchThreshold,
    );
    if (!mounted) return;

    if (dialogOpen) Navigator.of(context, rootNavigator: true).pop();

    setState(() {
      _step        = _MatchStep.idle;
      _matchResult = (result != null && result.isMatch) ? result : null;
    });

    final livePct = (liveness.score * 100).toStringAsFixed(1);

    if (result == null || !result.isMatch) {
      if (result != null && result.matchedFace != null) {
        _showSnack(
          'Liveness: $livePct% · No match — closest: ${result.matchedFace!.name} (${result.score.toStringAsFixed(1)}%). Try again.',
        );
      } else {
        _showSnack('Liveness: $livePct% · No face detected — please try again.');
      }
    } else {
      _showSnack('Liveness: $livePct% · Match: ${result.score.toStringAsFixed(1)}% — Identity verified.');
    }
  }

  void _showSnack(String msg, {Duration duration = const Duration(seconds: 4)}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(msg, style: const TextStyle(color: Colors.white)),
        backgroundColor: _kTextPri,
        behavior: SnackBarBehavior.floating,
        duration: duration,
      ),
    );
  }

  Future<void> _removeEnrolled(EnrolledFace face) async {
    await FaceStore.remove(face.id);
    _reload();
    _showSnack('${face.name} removed.');
  }

  @override
  Widget build(BuildContext context) {
    final busy = _step != _MatchStep.idle;

    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 20),

              // ── Header ────────────────────────────────────────────────────
              Row(children: [
                // FaceNova logo
                Image.asset(
                  'assets/icon/facenova_logo.png',
                  width: 48,
                  height: 48,
                ),
                const SizedBox(width: 12),
                const Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('FaceNova',
                          style: TextStyle(
                              color: _kTextPri,
                              fontSize: 18,
                              fontWeight: FontWeight.w800,
                              letterSpacing: -0.3)),
                      Text('100% offline · on-device AI',
                          style: TextStyle(color: _kTextHint, fontSize: 12)),
                    ],
                  ),
                ),
                _IconBtn(
                  icon: Icons.storefront_rounded,
                  onTap: () => Navigator.push(context,
                    MaterialPageRoute(builder: (_) => const StorePreviewScreen())),
                ),
                const SizedBox(width: 8),
                _IconBtn(
                  icon: Icons.tune_rounded,
                  onTap: () async {
                    await Navigator.push(context,
                      MaterialPageRoute(builder: (_) => const SettingsScreen()));
                    setState(() {});
                  },
                ),
              ]),

              const SizedBox(height: 24),

              // ── Divider ───────────────────────────────────────────────────
              const Divider(color: _kBorder, height: 1),

              const SizedBox(height: 20),

              // ── Enrolled Faces header ─────────────────────────────────────
              Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
                const Text('Enrolled Faces',
                    style: TextStyle(
                        color: _kTextPri,
                        fontSize: 14,
                        fontWeight: FontWeight.w700)),
                TextButton.icon(
                  onPressed: busy || !LivenessFlutter.isInitialized ? null : _enrollFromGallery,
                  icon: const Icon(Icons.add_photo_alternate_rounded,
                      size: 16, color: _kBlueMid),
                  label: const Text('Add from Gallery',
                      style: TextStyle(color: _kBlueMid, fontSize: 13)),
                ),
              ]),

              const SizedBox(height: 10),

              // ── Enrolled list / empty state ────────────────────────────────
              if (_enrolling)
                _SurfaceCard(
                  child: const Row(children: [
                    SizedBox(
                      width: 18, height: 18,
                      child: CircularProgressIndicator(strokeWidth: 2, color: _kBlue),
                    ),
                    SizedBox(width: 12),
                    Text('Detecting face…',
                        style: TextStyle(color: _kTextSec, fontSize: 13)),
                  ]),
                )
              else if (_enrolled.isEmpty)
                _SurfaceCard(
                  child: const Row(children: [
                    Icon(Icons.person_add_alt_1_rounded, color: _kTextHint, size: 20),
                    SizedBox(width: 12),
                    Text('No faces enrolled yet',
                        style: TextStyle(color: _kTextHint, fontSize: 13)),
                  ]),
                )
              else
                SizedBox(
                  height: 100,
                  child: ListView.separated(
                    scrollDirection: Axis.horizontal,
                    itemCount: _enrolled.length,
                    separatorBuilder: (_, __) => const SizedBox(width: 12),
                    itemBuilder: (_, i) => _EnrolledCard(
                      face: _enrolled[i],
                      onRemove: () => _removeEnrolled(_enrolled[i]),
                    ),
                  ),
                ),

              const SizedBox(height: 20),

              // ── Result / status area ───────────────────────────────────────
              if (_livenessFailResult != null)
                _LivenessFailCard(result: _livenessFailResult!)
              else if (_matchResult != null)
                _MatchResultCard(result: _matchResult!),

              const Spacer(),

              // ── Action button ──────────────────────────────────────────────
              _ActionButton(
                label: busy
                    ? 'Running…'
                    : !LivenessFlutter.isInitialized
                        ? 'Loading SDK…'
                        : 'Start Face Match',
                icon: Icons.manage_accounts_rounded,
                disabled: busy || !LivenessFlutter.isInitialized,
                onTap: _startFaceMatch,
              ),

              const SizedBox(height: 10),
              _SdkStatus(),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared surface card
// ─────────────────────────────────────────────────────────────────────────────

class _SurfaceCard extends StatelessWidget {
  final Widget child;
  const _SurfaceCard({required this.child});
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 16),
      decoration: BoxDecoration(
        color: _kSurface,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: _kBorder),
      ),
      child: child,
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Icon button (top-right)
// ─────────────────────────────────────────────────────────────────────────────

class _IconBtn extends StatelessWidget {
  final IconData icon;
  final VoidCallback onTap;
  const _IconBtn({required this.icon, required this.onTap});
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(10),
        decoration: BoxDecoration(
          color: _kSurface,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: _kBorder),
        ),
        child: Icon(icon, color: _kTextSec, size: 20),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Verifying dialog
// ─────────────────────────────────────────────────────────────────────────────

class _VerifyingDialog extends StatelessWidget {
  const _VerifyingDialog();
  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Colors.white,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 32),
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          Row(children: [
            Container(
              width: 32, height: 32,
              decoration: const BoxDecoration(shape: BoxShape.circle, color: _kGreen),
              child: const Icon(Icons.check_rounded, color: Colors.white, size: 18),
            ),
            const SizedBox(width: 14),
            const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Text('Step 1', style: TextStyle(color: _kTextHint, fontSize: 11)),
              Text('Liveness Passed',
                  style: TextStyle(color: _kGreen, fontSize: 15, fontWeight: FontWeight.w700)),
            ]),
          ]),
          const SizedBox(height: 6),
          Container(width: 2, height: 20, color: _kBorder, margin: const EdgeInsets.only(left: 15)),
          const SizedBox(height: 6),
          Row(children: [
            SizedBox(
              width: 32, height: 32,
              child: CircularProgressIndicator(strokeWidth: 3, color: _kBlue),
            ),
            const SizedBox(width: 14),
            const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Text('Step 2', style: TextStyle(color: _kTextHint, fontSize: 11)),
              Text('Comparing Face…',
                  style: TextStyle(color: _kBlue, fontSize: 15, fontWeight: FontWeight.w700)),
            ]),
          ]),
        ]),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Liveness fail card
// ─────────────────────────────────────────────────────────────────────────────

class _LivenessFailCard extends StatelessWidget {
  final LivenessResult result;
  const _LivenessFailCard({required this.result});
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: _kRed.withValues(alpha: 0.06),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: _kRed.withValues(alpha: 0.25)),
      ),
      child: Row(children: [
        if (result.imageBytes != null) ...[
          Container(
            width: 56, height: 56,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              border: Border.all(color: _kRed, width: 2),
            ),
            child: ClipOval(child: Image.memory(result.imageBytes!, fit: BoxFit.cover)),
          ),
          const SizedBox(width: 14),
        ],
        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          const Row(children: [
            Icon(Icons.block_rounded, color: _kRed, size: 16),
            SizedBox(width: 6),
            Text('Liveness Check Failed',
                style: TextStyle(color: _kRed, fontSize: 13, fontWeight: FontWeight.w700)),
          ]),
          const SizedBox(height: 4),
          Text('Score: ${(result.score * 100).toStringAsFixed(1)}%  · Please try again',
              style: const TextStyle(color: _kTextSec, fontSize: 12)),
        ])),
      ]),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Match result card
// ─────────────────────────────────────────────────────────────────────────────

class _MatchResultCard extends StatelessWidget {
  final FaceMatchResult result;
  const _MatchResultCard({required this.result});

  @override
  Widget build(BuildContext context) {
    final color    = result.isMatch ? _kGreen : _kRed;
    final enrolled = result.matchedFace?.photo;
    final captured = result.capturedImage;

    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.06),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: color.withValues(alpha: 0.25)),
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          Icon(result.isMatch ? Icons.how_to_reg_rounded : Icons.person_off_rounded,
              color: color, size: 16),
          const SizedBox(width: 8),
          Flexible(child: Text(
            result.isMatch
                ? 'Identity Verified · ${result.matchedFace?.name ?? ''}'
                : 'No Match Found',
            style: TextStyle(color: color, fontSize: 13, fontWeight: FontWeight.w700),
          )),
        ]),
        const SizedBox(height: 4),
        Text('Confidence: ${result.score.toStringAsFixed(1)}%',
            style: const TextStyle(color: _kTextSec, fontSize: 12)),

        if (enrolled != null && captured != null) ...[
          const SizedBox(height: 14),
          Row(children: [
            Expanded(child: _FacePhoto(bytes: enrolled, label: 'Enrolled', borderColor: _kBorder)),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 10),
              child: Icon(
                result.isMatch ? Icons.check_circle_rounded : Icons.cancel_rounded,
                color: color, size: 26,
              ),
            ),
            Expanded(child: _FacePhoto(bytes: captured, label: 'Captured', borderColor: color)),
          ]),
        ],
      ]),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Face photo widget
// ─────────────────────────────────────────────────────────────────────────────

class _FacePhoto extends StatelessWidget {
  final Uint8List bytes;
  final String label;
  final Color borderColor;
  const _FacePhoto({required this.bytes, required this.label, required this.borderColor});

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Container(
        width: 70, height: 70,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          border: Border.all(color: borderColor, width: 2),
        ),
        child: ClipOval(child: Image.memory(bytes, fit: BoxFit.cover)),
      ),
      const SizedBox(height: 5),
      Text(label,
          style: const TextStyle(color: _kTextHint, fontSize: 11,
              fontWeight: FontWeight.w500)),
    ]);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Enrolled face card
// ─────────────────────────────────────────────────────────────────────────────

class _EnrolledCard extends StatelessWidget {
  final EnrolledFace face;
  final VoidCallback onRemove;
  const _EnrolledCard({required this.face, required this.onRemove});

  @override
  Widget build(BuildContext context) {
    return Column(mainAxisSize: MainAxisSize.min, children: [
      Stack(children: [
        Container(
          width: 64, height: 64,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            border: Border.all(color: _kBlue, width: 2),
          ),
          child: ClipOval(
            child: Image.memory(face.photo, fit: BoxFit.cover),
          ),
        ),
        Positioned(
          top: 0, right: 0,
          child: GestureDetector(
            onTap: onRemove,
            child: Container(
              padding: const EdgeInsets.all(2),
              decoration: const BoxDecoration(
                shape: BoxShape.circle,
                color: _kRed,
              ),
              child: const Icon(Icons.close, size: 12, color: Colors.white),
            ),
          ),
        ),
      ]),
      const SizedBox(height: 6),
      SizedBox(
        width: 68,
        child: Text(face.name,
            textAlign: TextAlign.center,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: const TextStyle(color: _kTextSec, fontSize: 11)),
      ),
    ]);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Action button
// ─────────────────────────────────────────────────────────────────────────────

class _ActionButton extends StatelessWidget {
  final String label;
  final IconData icon;
  final bool disabled;
  final VoidCallback onTap;
  const _ActionButton({
    required this.label, required this.icon,
    required this.disabled, required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: disabled ? 0.5 : 1.0,
      child: FilledButton.icon(
        onPressed: disabled ? null : onTap,
        icon: Icon(icon, color: Colors.white, size: 20),
        label: Text(label,
            style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w700,
                color: Colors.white)),
        style: FilledButton.styleFrom(
          backgroundColor: _kBlue,
          disabledBackgroundColor: _kBlue,
          minimumSize: const Size(double.infinity, 52),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SDK status row
// ─────────────────────────────────────────────────────────────────────────────

class _SdkStatus extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final ok = LivenessFlutter.isInitialized;
    return Row(mainAxisAlignment: MainAxisAlignment.center, children: [
      Icon(ok ? Icons.check_circle_rounded : Icons.cancel_rounded,
          size: 12,
          color: ok ? _kGreen : _kRed),
      const SizedBox(width: 5),
      Text(
        ok ? 'SDK initialized · offline' : 'SDK not initialized — check license key',
        style: TextStyle(fontSize: 11,
            color: ok ? _kTextHint : _kRed),
      ),
    ]);
  }
}
